# Portfolio Variance

In [1]:
import numpy as np
import pandas as pd
import time
import os
# import quiz_helper
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (14, 8)

### data bundle

In [3]:
import os
# import quiz_helper
from zipline.data import bundles

In [4]:

import zipline.data.bundles as bundles
import pandas as pd
from zipline.data.bundles import register, yahoo_NYSE, csvdir

# Specify the bundle name
bundle_name = 'yahoo_NYSE'

start_session = pd.Timestamp('2013-07-01')  # Timezone-naive
end_session = pd.Timestamp('2017-06-30')    # Timezone-naive


register(
    'yahoo_NYSE',
    yahoo_NYSE.yahoo_NYSE(
        tframes=["daily"],
        csvdir="/home/ankit/AI_for_trading/Data/data/eod-quotemedia/"
    )
)

bundle_data = bundles.load('yahoo_NYSE')

/tmp/ipykernel_4027/1568509080.py:12: UserWarning: Overwriting bundle with name 'yahoo_NYSE'
  register(


### Build pipeline engine

In [7]:
from zipline.pipeline import Pipeline
from zipline.pipeline.factors import AverageDollarVolume
from zipline.utils.calendar_utils import get_calendar
from zipline.pipeline import engine
from zipline.pipeline.loaders import USEquityPricingLoader
from zipline.pipeline.data import USEquityPricing

def choose_price_loader(column):
    if column not in USEquityPricing.columns:
        print("Column not in USEquityPricing.columns")
    return pricing_loader

universe = AverageDollarVolume(window_length=120).top(500) 
trading_calendar = get_calendar('NYSE') 

# Set the dataloader
pricing_loader = USEquityPricingLoader(bundle_data.equity_daily_bar_reader, bundle_data.adjustment_reader,fx_reader=None)


engine = engine.SimplePipelineEngine(choose_price_loader,asset_finder=bundle_data.asset_finder)

### View Data¶
With the pipeline engine built, let's get the stocks at the end of the period in the universe we're using. We'll use these tickers to generate the returns data for the our risk model.

In [8]:
from zipline.pipeline.domain import US_EQUITIES

universe_end_date = pd.Timestamp('2017-01-06')

universe_tickers = engine\
    .run_pipeline(
        Pipeline(screen=universe,domain=US_EQUITIES),
        universe_end_date,
        universe_end_date)\
    .index.get_level_values(1)\
    .values.tolist()
    
universe_tickers

[Equity(0 [A]),
 Equity(1 [AAL]),
 Equity(2 [AAP]),
 Equity(3 [AAPL]),
 Equity(4 [ABBV]),
 Equity(5 [ABT]),
 Equity(6 [ACN]),
 Equity(7 [ADBE]),
 Equity(8 [ADI]),
 Equity(9 [ADM]),
 Equity(10 [ADP]),
 Equity(11 [ADSK]),
 Equity(12 [AEE]),
 Equity(13 [AEP]),
 Equity(14 [AES]),
 Equity(15 [AET]),
 Equity(16 [AFL]),
 Equity(17 [AIG]),
 Equity(18 [AIV]),
 Equity(19 [AIZ]),
 Equity(20 [AJG]),
 Equity(21 [AKAM]),
 Equity(22 [ALB]),
 Equity(23 [ALGN]),
 Equity(24 [ALK]),
 Equity(25 [ALL]),
 Equity(26 [AMAT]),
 Equity(27 [AMD]),
 Equity(28 [AME]),
 Equity(29 [AMG]),
 Equity(30 [AMGN]),
 Equity(31 [AMP]),
 Equity(32 [AMT]),
 Equity(33 [AMZN]),
 Equity(34 [ANDV]),
 Equity(35 [ANSS]),
 Equity(36 [AON]),
 Equity(37 [AOS]),
 Equity(38 [APA]),
 Equity(39 [APD]),
 Equity(40 [APH]),
 Equity(41 [ARE]),
 Equity(42 [AVB]),
 Equity(43 [AVGO]),
 Equity(44 [AVY]),
 Equity(45 [AWK]),
 Equity(46 [AXP]),
 Equity(47 [AYI]),
 Equity(48 [AZO]),
 Equity(49 [BA]),
 Equity(50 [BAC]),
 Equity(51 [BAX]),
 Equity(52 [B

In [ ]:
len(universe_tickers)

In [9]:
from zipline.data.data_portal import DataPortal

data_portal = DataPortal(
    bundle_data.asset_finder,
    trading_calendar=trading_calendar,
    first_trading_day=bundle_data.equity_daily_bar_reader.first_trading_day,
    equity_minute_reader=None,
    equity_daily_reader=bundle_data.equity_daily_bar_reader,
    adjustment_reader=bundle_data.adjustment_reader)

## Get pricing data helper function

In [ ]:
from quiz_helper import get_pricing

## get pricing data into a dataframe

In [10]:

def get_pricing(data_portal, trading_calendar, assets, start_date, end_date, field='close'):
    end_dt = pd.Timestamp(end_date.strftime('%Y-%m-%d'))
    start_dt = pd.Timestamp(start_date.strftime('%Y-%m-%d'))

    end_loc = trading_calendar.closes.index.get_loc(end_dt)
    start_loc = trading_calendar.closes.index.get_loc(start_dt)

    return data_portal.get_history_window(
        assets=assets,
        end_dt=end_dt,
        bar_count=end_loc - start_loc,
        frequency='1d',
        field=field,
        data_frequency='daily')

returns_df = \
    get_pricing(
        data_portal,
        trading_calendar,
        universe_tickers,
        universe_end_date - pd.DateOffset(years=2),
        universe_end_date)\
    .pct_change()[1:].fillna(0) #convert prices into returns

returns_df

Equity(0 [A])  Equity(1 [AAL])  Equity(2 [AAP])  Equity(3 [AAPL])  \
2015-01-08       0.029975         0.012262         0.008765          0.038384   
2015-01-09      -0.007337        -0.030563        -0.005089          0.001108   
2015-01-12      -0.011826        -0.046905        -0.008546         -0.024676   
2015-01-13      -0.013962         0.016539        -0.032530          0.008897   
2015-01-14      -0.012389        -0.019643        -0.019056         -0.003811   
...                   ...              ...              ...               ...   
2016-12-30      -0.001753        -0.011852        -0.006812         -0.007813   
2017-01-03       0.020413        -0.008353         0.008751          0.002867   
2017-01-04       0.013121         0.008639         0.008206         -0.001136   
2017-01-05      -0.011890        -0.017345        -0.000698          0.005103   
2017-01-06       0.031156         0.006973        -0.013091          0.011148   

            Equity(4 [ABBV])  Equity(5 [ABT])  Equity(6 [ACN])  \
2015-01-08          0.010459         0.020554         0.015249   
2015-01-09         -0.027355        -0.010508        -0.001113   
2015-01-12         -0.000304         0.008407        -0.003007   
2015-01-13         -0.036040        -0.021281         0.003575   
2015-01-14          0.004890        -0.007397        -0.011689   
...                      ...              ...              ...   
2016-12-30         -0.001754         0.002610         0.001026   
2017-01-03         -0.003354         0.016662        -0.005720   
2017-01-04          0.014100         0.007939         0.002404   
2017-01-05          0.007584         0.008638        -0.014991   
2017-01-06          0.000314         0.027204         0.011392   

            Equity(7 [ADBE])  Equity(8 [ADI])  Equity(9 [ADM])  ...  \
2015-01-08          0.025454         0.017655        -0.014609  ...   
2015-01-09         -0.014811        -0.000730        -0.008530  ...   
2015-01-12         -0.010022        -0.010051        -0.012495  ...   
2015-01-13         -0.007452        -0.011445         0.001452  ...   
2015-01-14         -0.008500        -0.000747        -0.017191  ...   
...                      ...              ...              ...  ...   
2016-12-30         -0.007041        -0.013047         0.006393  ...   
2017-01-03          0.005148        -0.001515         0.011829  ...   
2017-01-04          0.006378        -0.002069        -0.001732  ...   
2017-01-05          0.016996        -0.014373        -0.007374  ...   
2017-01-06          0.022566         0.003926        -0.022941  ...   

            Equity(398 [WYNN])  Equity(399 [XEL])  Equity(400 [XOM])  \
2015-01-08            0.012031           0.011599           0.016645   
2015-01-09            0.012499          -0.012285          -0.001410   
2015-01-12           -0.003958          -0.008845          -0.019218   
2015-01-13            0.009093           0.008087          -0.003653   
2015-01-14           -0.008077           0.008852          -0.002889   
...                        ...                ...                ...   
2016-12-30           -0.007571          -0.005862          -0.000996   
2017-01-03            0.010981          -0.001966           0.006980   
2017-01-04            0.032243           0.004431          -0.011002   
2017-01-05            0.012849           0.000000          -0.014907   
2017-01-06            0.010827           0.002941          -0.000565   

            Equity(401 [XRAY])  Equity(402 [XRX])  Equity(403 [XYL])  \
2015-01-08            0.024689           0.027531           0.007546   
2015-01-09           -0.014569          -0.005798          -0.018863   
2015-01-12           -0.009477          -0.010199          -0.021770   
2015-01-13           -0.003062           0.005166           0.002312   
2015-01-14           -0.014587           0.004389          -0.006344   
...                        ...                ...                ...   
2016-12-30           -0.

## Let's look at a two stock portfolio

Let's pretend we have a portfolio of two stocks.  We'll pick Apple and Microsoft in this example.

In [11]:
aapl_col = returns_df.columns[3]
msft_col = returns_df.columns[312]
asset_return_1 = returns_df[aapl_col].rename('asset_return_aapl')
asset_return_2 = returns_df[msft_col].rename('asset_return_msft')
asset_return_df = pd.concat([asset_return_1,asset_return_2],axis=1)
asset_return_df.head(2)

asset_return_aapl  asset_return_msft
2015-01-08           0.038384           0.010579
2015-01-09           0.001108          -0.001208

## Factor returns
Let's make up a "factor" by taking an average of all stocks in our list.  You can think of this as an equal weighted index of the 490 stocks, kind of like a measure of the "market".  We'll also make another factor by calculating the median of all the stocks.  These are mainly intended to help us generate some data to work with.  We'll go into how some common risk factors are generated later in the lessons.

Also note that we're setting axis=1 so that we calculate a value for each time period (row) instead of one value for each column (assets).

In [12]:
factor_return_1 = returns_df.mean(axis=1)
factor_return_2 = returns_df.median(axis=1)
factor_return_l = [factor_return_1, factor_return_2]

## Factor exposures

Factor exposures refer to how "exposed" a stock is to each factor.  We'll get into this more later.  For now, just think of this as one number for each stock, for each of the factors.

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
"""
For now, just assume that we're calculating a number for each 
stock, for each factor, which represents how "exposed" each stock is
to each factor. 
We'll discuss how factor exposure is calculated later in the lessons.
"""
def get_factor_exposures(factor_return_l, asset_return):
    lr = LinearRegression()
    X = np.array(factor_return_l).T
    y = np.array(asset_return.values)
    lr.fit(X,y)
    return lr.coef_

In [15]:
factor_exposure_l = []
for i in range(len(asset_return_df.columns)):
    factor_exposure_l.append(
        get_factor_exposures(factor_return_l,
                             asset_return_df[asset_return_df.columns[i]]
                            ))
    
factor_exposure_a = np.array(factor_exposure_l)

In [16]:
print(f"factor_exposures for asset 1 {factor_exposure_a[0]}")
print(f"factor_exposures for asset 2 {factor_exposure_a[1]}")

factor_exposures for asset 1 [0.74250549 0.20961105]
factor_exposures for asset 2 [ 2.56672727 -1.64001956]


## Variance of stock 1

Calculate the variance of stock 1.  
$\textrm{Var}(r_{1}) = \beta_{1,1}^2 \textrm{Var}(f_{1}) + \beta_{1,2}^2 \textrm{Var}(f_{2}) + 2\beta_{1,1}\beta_{1,2}\textrm{Cov}(f_{1},f_{2}) + \textrm{Var}(s_{1})$

In [18]:
factor_exposure_1_1 = factor_exposure_a[0][0]
factor_exposure_1_2 = factor_exposure_a[0][1]
common_return_1 = factor_exposure_1_1 * factor_return_1 + factor_exposure_1_2 * factor_return_2
specific_return_1 = asset_return_1 - common_return_1

In [19]:
covm_f1_f2 = np.cov(factor_return_1,factor_return_2,ddof=1) #this calculates a covariance matrix
# get the variance of each factor, and covariances from the covariance matrix covm_f1_f2
var_f1 = covm_f1_f2[0,0]
var_f2 = covm_f1_f2[1,1]
cov_f1_f2 = covm_f1_f2[0][1]

# calculate the specific variance.  
var_s_1 = np.var(specific_return_1,ddof=1)

# calculate the variance of asset 1 in terms of the factors and specific variance
var_asset_1 = (factor_exposure_1_1**2 * var_f1) + \
              (factor_exposure_1_2**2 * var_f2) + \
              2 * (factor_exposure_1_1 * factor_exposure_1_2 * cov_f1_f2) + \
              var_s_1
print(f"variance of asset 1: {var_asset_1:.8f}")

variance of asset 1: 0.00024787


## Variance of stock 2
Calculate the variance of stock 2.  
$\textrm{Var}(r_{2}) = \beta_{2,1}^2 \textrm{Var}(f_{1}) + \beta_{2,2}^2 \textrm{Var}(f_{2}) + 2\beta_{2,1}\beta_{2,2}\textrm{Cov}(f_{1},f_{2}) + \textrm{Var}(s_{2})$

In [20]:
factor_exposure_2_1 = factor_exposure_a[1][0]
factor_exposure_2_2 = factor_exposure_a[1][1]
common_return_2 = factor_exposure_2_1 * factor_return_1 + factor_exposure_2_2 * factor_return_2
specific_return_2 = asset_return_2 - common_return_2

In [21]:
# Notice we already calculated the variance and covariances of the factors

# calculate the specific variance of asset 2
var_s_2 = np.var(specific_return_2,ddof=1)

# calcualte the variance of asset 2 in terms of the factors and specific variance
var_asset_2 = (factor_exposure_2_1**2 * var_f1) + \
              (factor_exposure_2_2**2 * var_f2) + \
              (2 * factor_exposure_2_1 * factor_exposure_2_2 * cov_f1_f2) + \
              var_s_2
            
print(f"variance of asset 2: {var_asset_2:.8f}")

variance of asset 2: 0.00034966


## Covariance of stocks 1 and 2
Calculate the covariance of stock 1 and 2.  
$\textrm{Cov}(r_{1},r_{2}) = \beta_{1,1}\beta_{2,1}\textrm{Var}(f_{1}) + \beta_{1,1}\beta_{2,2}\textrm{Cov}(f_{1},f_{2}) + \beta_{1,2}\beta_{2,1}\textrm{Cov}(f_{1},f_{2}) + \beta_{1,2}\beta_{2,2}\textrm{Var}(f_{2})$

In [22]:
# TODO: calculate the covariance of assets 1 and 2 in terms of the factors
cov_asset_1_2 = (factor_exposure_1_1 * factor_exposure_2_1 * var_f1) + \
            (factor_exposure_1_1 * factor_exposure_2_2 * cov_f1_f2) + \
            (factor_exposure_1_2 * factor_exposure_2_1 * cov_f1_f2) + \
            (factor_exposure_1_2 * factor_exposure_2_2 * var_f2)
print(f"covariance of assets 1 and 2: {cov_asset_1_2:.8f}")

covariance of assets 1 and 2: 0.00008220


## Quiz 1: calculate portfolio variance

We'll choose stock weights for now (in a later lesson, you'll learn how to use portfolio optimization that uses alpha factors and a risk factor model to choose stock weights).

$\textrm{Var}(r_p) = x_{1}^{2} \textrm{Var}(r_1) + x_{2}^{2} \textrm{Var}(r_2) + 2x_{1}x_{2}\textrm{Cov}(r_{1},r_{2})$ 

In [23]:
weight_1 = 0.60
weight_2 = 0.40

# TODO: calculate portfolio variance
var_portfolio = (weight_1**2)*var_asset_1 + (weight_2**2)*var_asset_2 + 2*weight_1*weight_2*cov_asset_1_2
print(f"variance of portfolio is {var_portfolio:.8f}")

variance of portfolio is 0.00018463


## Quiz 2: Do it with Matrices!

Create matrices $\mathbf{F}$, $\mathbf{B}$ and $\mathbf{S}$, where  
$\mathbf{F}= \begin{pmatrix}
\textrm{Var}(f_1) & \textrm{Cov}(f_1,f_2) \\ 
\textrm{Cov}(f_2,f_1) & \textrm{Var}(f_2) 
\end{pmatrix}$
is the covariance matrix of factors,  

$\mathbf{B} = \begin{pmatrix}
\beta_{1,1}, \beta_{1,2}\\ 
\beta_{2,1}, \beta_{2,2}
\end{pmatrix}$ 
is the matrix of factor exposures, and  

$\mathbf{S} = \begin{pmatrix}
\textrm{Var}(s_i) & 0\\ 
0 & \textrm{Var}(s_j)
\end{pmatrix}$
is the matrix of specific variances.  

$\mathbf{X} = \begin{pmatrix}
x_{1} \\
x_{2}
\end{pmatrix}$

### Concept Question
What are the dimensions of the $\textrm{Var}(r_p)$ portfolio variance?  Given this, when choosing whether to multiply a row vector or a column vector on the left and right sides of the $\mathbf{BFB}^T$, which choice helps you get the dimensions of the portfolio variance term?

In other words:
Given that $\mathbf{X}$ is a column vector, which makes more sense?

$\mathbf{X}^T(\mathbf{BFB}^T + \mathbf{S})\mathbf{X}$ ?  
or  
$\mathbf{X}(\mathbf{BFB}^T + \mathbf{S})\mathbf{X}^T$ ?  

## Answer 2 here:

## Quiz 3: Calculate portfolio variance using matrices

In [26]:
# TODO: covariance matrix of factors
F = np.array([[var_f1,cov_f1_f2],[cov_f1_f2,var_f2]])
F

array([[8.68160759e-05, 8.23771990e-05],
       [8.23771990e-05, 7.93155979e-05]])

In [40]:
# TODO: matrix of factor exposures
B = np.array([[factor_exposure_1_1,factor_exposure_1_2],[factor_exposure_2_1,factor_exposure_2_2]])
B

array([[ 0.74250549,  0.20961105],
       [ 2.56672727, -1.64001956]])

In [41]:
# TODO: matrix of specific variances
S = np.array([[var_s_1,0],[0,var_s_2]])
S

array([[0.00017088, 0.        ],
       [0.        , 0.00025791]])

#### Hint for column vectors
Try using [reshape](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.reshape.html)

In [42]:
# TODO: make a column vector for stock weights matrix X
X = np.array([weight_1,weight_2]).reshape(2,1)
X

array([[0.6],
       [0.4]])

In [43]:
# TODO: covariance matrix of assets
var_portfolio = X.T.dot(B.dot(F).dot(B.T)+S).dot(X)
print(f"portfolio variance is \n{var_portfolio[0][0]:.8f}")

portfolio variance is 
0.00018463


## Solution
[Solution notebook is here](portfolio_variance_solution.ipynb)